### ISSUE TITLE
routes stay active when in boss fight

### ISSUE THREAD

**Issue by Bwopp** [yourboykyle/SecretRoutes#1]
the routes from the last room I was in are still showing up in the Necron fight

![image](https://github.com/yourboykyle/SecretRoutes/assets/91853469/c1627e19-0b1d-4bff-8cdc-d0896eadf725)

**Comment by yourboykyle** [comment]
Fixed the issue. If you have further requests, ask me on discord (I'm more active there): https://discord.gg/M7aN8EsfR7

Anyways go download the new release: https://github.com/yourboykyle/SecretRoutes/releases/tag/v0.2.1
