### ISSUE TITLE
can you make it so that you run from just 3 harder rooms

### ISSUE THREAD

**Issue by BladedEdge** [yourboykyle/SecretRoutes#19]
[SecretRoutes-main.zip](https://github.com/user-attachments/files/16815058/SecretRoutes-main.zip)
[routes.json](https://github.com/user-attachments/files/16815059/routes.json)

here you go

ive already done it so that you needa just make a new branch or whatever odin does

**Comment by yourboykyle** [comment]
Won’t be adding this in
