### ISSUE TITLE
Routes showing up in places that are not duengeons

### ISSUE THREAD

**Issue by Bwopp** [yourboykyle/SecretRoutes#2]
It may have been because I got kicked to limbo but the routes are showing up in the hub.

![image](https://github.com/yourboykyle/SecretRoutes/assets/91853469/bb724abc-bf33-4ff9-b65e-0b8e1bb71aa9)

after disconnecting and reconnecting

![image](https://github.com/yourboykyle/SecretRoutes/assets/91853469/379391c6-8fc7-471f-b16f-0d4e005867cb)

just want to add I like the concept of the mod and it's helping me learn routes thanks.

**Comment by Bwopp** [comment]
I just did some testing and all the highlights are showing at 0, 0.

**Comment by yourboykyle** [comment]
Fixed in recent commit, will be in release v0.2.2
