### ISSUE TITLE
Is the devPassword supposed to be visible or am I misunderstanding something?

### ISSUE THREAD

**Issue by LetsPlayKeks** [yourboykyle/SecretRoutes#31]
https://github.com/yourboykyle/SecretRoutes/blob/f21a5c363f69508ead507af59cd6a6315b6ba9f2/src/main/java/xyz/yourboykyle/secretroutes/config/SRMConfig.java#L1190

If this is supposed to be visible, just discard this or say something funny, idk.

Cheers

**Comment by yourboykyle** [comment]
> https://github.com/yourboykyle/SecretRoutes/blob/f21a5c363f69508ead507af59cd6a6315b6ba9f2/src/main/java/xyz/yourboykyle/secretroutes/config/SRMConfig.java#L1190
> 
> If this is supposed to be visible, just discard this or say something funny, idk.
> 
> Cheers

What do you mean? You type this into the dev section in the config and it will show the dev options
